//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LICTProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.ProjectMembers = new HashSet<ProjectMember>();
        }
    
        public int PersonnelID { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> LICT_Title { get; set; }
        public string PostAtIOE { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string Urls { get; set; }
        public byte[] Image { get; set; }

        public HttpPostedFileBase UploadImages { get; set; }
        public virtual LICT_Title LICT_Title1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMember> ProjectMembers { get; set; }
    }
}
