//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LICTProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectMembers = new HashSet<ProjectMember>();
            this.OtherMembers = new HashSet<OtherMember>();
        }
    
        public int ProjectID { get; set; }
        public string Project_Title { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> StartTime { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Duration { get; set; }
        public string Describe { get; set; }
        public string GrantProvider { get; set; }
        public string GrantAmt { get; set; }
        public string UniqueId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMember> ProjectMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherMember> OtherMembers { get; set; }
    }
}
