//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LICTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMember
    {
        public int ProjectMembersID { get; set; }
        public int ProjectID { get; set; }
        public int PersonnelID { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual Project Project { get; set; }
    }
    //to store data obtain from client as JSON;; refer at ProjectsController-->setProjectMember
    public class ListMember
    {
        public Members[] property { get; set; }
    }
    public class Members
    {
        public string ProjectID { get; set; }
        public string PersonnelID { get; set; }
    }

    public class ListOtherMember
    {
        public OtherMembers[] property { get; set; }
    }
    public class OtherMembers
    {
        public string ProjectID { get; set; }
        public string OtherMember { get; set; }
    }
}
